export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const SEARCHED_MOVIES = "SEARCHED_MOVIES";
export const SWITCHNAVBAR = "SWITCHNAVBAR";
